Repository SOPT31-GROUP3/coupang-frontend, pull requests merged in 2022-11, with the labels that each got.

#6 [feat/cart-ui] 장바구니 페이지 UI 퍼블리싱
  src/assets/images/icon_basket_main.svg
  src/assets/images/index.ts
  src/components/cart/CartComponent.tsx
  src/components/cart/EmptyCartView.tsx
  src/pages/Cart.tsx
Labels: feat, design

#7 [feat/common-nav] nav 컴포넌트 구현
  src/App.tsx
  src/assets/icons/ic_category_bar.svg
  src/assets/icons/ic_home_bar.svg
  src/assets/icons/ic_mycoupang_bar.svg
  src/assets/icons/ic_search_bar.svg
  src/assets/icons/index.ts
  src/components/common/NavBar.tsx
  src/components/common/Router.tsx
  src/index.tsx
  src/styles/GlobalStyle.tsx
Labels: feat

#14 [feat/common-product] product 컴포넌트 구현
  src/assets/icons/icon_star.svg
  src/assets/icons/index.ts
  src/components/common/Product.tsx
Labels: design

#12 [feat/common-header] header 컴포넌트 구현
  src/assets/icons/icon_basket_btn.svg
  src/assets/icons/icon_category_btn.svg
  src/assets/icons/icon_search_btn.svg
  src/assets/icons/index.ts
  src/assets/images/img_logo.svg
  src/assets/images/index.ts
  src/components/common/Header.tsx
  src/components/common/Router.tsx
Labels: feat

#11 [feat/mypage-ui] 마이쿠팡 페이지 UI 퍼블리싱
  src/assets/icons/icon_arrow.svg
  src/assets/icons/icon_cancellist.svg
  src/assets/icons/icon_coupon.svg
  src/assets/icons/icon_credit.svg
  src/assets/icons/icon_customercenter.svg
  src/assets/icons/icon_deliver.svg
  src/assets/icons/icon_gift.svg
  src/assets/icons/icon_orderlist.svg
  src/assets/icons/icon_profile.svg
  src/assets/icons/icon_review.svg
  src/assets/icons/icon_rocketfresh.svg
  src/assets/icons/index.ts
  src/components/mypage/MyPageComponent.tsx
  src/components/mypage/MyPageView.tsx
  src/pages/MyPage.tsx
Labels: feat, design

#15 [feat/home-banner] 홈 배너 캐러셀 슬라이드 및 서비스 메뉴 퍼블리싱
  package-lock.json
  package.json
  src/assets/images/img_event.svg
  src/assets/images/img_homebannerfirst.svg
  src/assets/images/img_homebannersecond.svg
  src/assets/images/img_homebannerthird.svg
  src/assets/images/img_regulardelivery.svg
  src/assets/images/img_roketdelivery.svg
  src/assets/images/img_roketshipping.svg
  src/assets/images/index.ts
  src/components/home/Carousel.tsx
  src/components/home/HomeComponent.tsx
  src/components/home/HomeServiceMenu.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: feat

#21 [feat/home-todayshot] 오늘의 상품 API 연결 및 TODAY'S HOT 컴포넌트 구현
  src/components/common/Product.tsx
  src/components/home/HomeTodaysHot.tsx
  src/libs/api.ts
  src/pages/Home.tsx
  src/types/types.ts
Labels: feat

#19 [Feat/mypage-api] 마이쿠팡 페이지 유저 정보 API 연결
  src/components/common/NavBar.tsx
  src/components/common/Router.tsx
  src/components/mypage/MyPageView.tsx
  src/libs/api.ts
  src/types/types.ts
Labels: feat

#20 [feat/category-menu] 카테고리 상단 메뉴 컴포넌트 구현
  src/assets/icons/icon_arrow_big.svg
  src/assets/icons/icon_arrow_big_last.svg
  src/assets/icons/icon_arrow_small.svg
  src/assets/icons/icon_button_top.svg
  src/assets/icons/icon_home_category.svg
  src/assets/icons/icon_page_arrow_left.svg
  src/assets/icons/icon_page_arrow_right.svg
  src/assets/icons/index.ts
  src/assets/images/img_menu_top_item.svg
  src/assets/images/index.ts
  src/components/category/ButtonTop.tsx
  src/components/category/CategoryComponent.tsx
  src/components/category/Menu.tsx
  src/components/category/ProductItem.tsx
  src/components/common/Header.tsx
  src/components/common/ProductWithProps.tsx
  src/components/home/HomeTodaysHot.tsx
  src/libs/api.ts
  src/pages/Category.tsx
  src/types/types.ts
  yarn.lock
Labels: feat, design
